version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "5000:5000"

  product-service:
    build:
      context: ./product-service
    ports:
      - "5001:5001"

  order-service:
    build:
      context: ./order-service
    ports:
      - "5002:5002"
