project_id           = "adept-cascade-441115-g6"
region               = "europe-west1"
zone                 = "europe-west1-b"
subnet_cidr          = "10.0.0.0/24"
node_machine_type    = "e2-micro"
bastion_machine_type = "e2-micro"
